[package]
name = "kqcabrelay"
version = "0.1.0"
authors = ["Christopher S. Corley <cscorley@gmail.com>"]
edition = "2018"

[dependencies]
websocket = "0.23.0"
reqwest = "0.9.22"
clap = "2.33.0"
log = "0.4"
fern = "0.5"
chrono = "0.4.9"
